#!/usr/bin/env bash

export CONTECO_LABEL="package.bash_api - ModEco"
export CONTECO_DESCRIPTION="The Modeco Bash API module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="bash_api"
export CONTECO_TAG="5.0.18"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
